import os
from dotenv import load_dotenv

load_dotenv()

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_SIGNATURE_NAME = os.getenv("AWS_S3_SIGNATURE_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_VERIFY = True
AWS_DEFAULT_ACL = None
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_FILE_OVERWRITE = False


print("AWS_ACCESS_KEY_ID", AWS_ACCESS_KEY_ID)
print('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)
print("AWS_STORAGE_BUCKET_NAME", AWS_STORAGE_BUCKET_NAME)
print("AWS_STORAGE_BUCKET_NAME",AWS_S3_SIGNATURE_NAME)
print('AWS_S3_REGION_NAME', AWS_S3_REGION_NAME)
print('AWS_S3_VERIFY', AWS_S3_VERIFY)
print('AWS_DEFAULT_ACL', AWS_DEFAULT_ACL)
print('AWS_S3_CUSTOM_DOMAIN', AWS_S3_CUSTOM_DOMAIN)
print('AWS_S3_FILE_OVERWRITE', AWS_S3_FILE_OVERWRITE)
